### ISSUE TITLE
General fixes on phase 2

### ISSUE THREAD

**Issue by abdelazizElemary** [Ahmed-Eloraby/Bld_Project_01#2] opened 2022-08-16 16:01 UTC
- The script file is not called from the html file, So the courses aren't rendered. This is an error in the CORS because you are using server
- you better place all the functions you need in one file and don't use imports

**Comment by Ahmed-Eloraby** [comment] 2022-08-16 16:52
1- I am calling the under the footer (first line before body closing tag), please make sure that you are on the master branch. 
2-I tried to make a separate script for each functionality for example : one script is responsible for dealing with the server and another on is responsible for the structure of any component (ex: course card). So should i assign tasks differently between  the scripts or should I gather all functionalities into one script since we are just working on a small project?

**Comment by Ahmed-Eloraby** [comment] 2022-08-16 17:03
the issue is that we are working on a local json-server and we need to type json-server --watch ./data/db.json in the terminal every time we open the application.

**Comment by abdelazizElemary** [comment] 2022-08-16 17:07
- yes I run the json-server to listen to the requests. Your code is ideal the way to break it through files and import is the right thing. But I was speaking because we are using json-server there is a problem with CORS headers when you use `type="module"`
- I checked from branch phase2 not from the master

**Comment by Ahmed-Eloraby** [comment] 2022-08-16 17:34
oh , apologies for that!
So, should I change the script type from module to javascript and put all functions in a single js file?

**Comment by abdelazizElemary** [comment] 2022-08-16 17:38
> oh , apologies for that! So, should I change the script type from module to javascript and put all functions in a single js file?

No problem at all
Or you can still have the clean structure but create an npm server to run this. It is easy if you are familiar with it. If not we can make it after the standup tomorrow and for now fix that error only.

**Closed as completed** 2022-08-19 17:16 UTC
